### ISSUE TITLE
Data path compilation

### ISSUE THREAD

**Issue by jgcodes2020** [branpk/wafel#27]
Hi @branpk,
Things are going quite well with Pancake. One problem that's nagging me is the issue of compiling and evaluating data paths. As it stands right now, I have no clue how Wafel is able to get correct values, since I usually end up dereferencing null pointers.

EDIT: I should make my question clearer.
- How do indirects work in the evaluator?
- Why is it that you use RVAs to access the DLL's address space?

**Comment by branpk** [comment]
> How do indirects work in the evaluator?

I'm not totally sure I understand the question, but Wafel data paths consist of an `Address` (relative to the image base address), and then a sequence of one of 3 operations:
* Add N bytes (i.e. turn a pointer to a struct into a pointer to a field)
* Dereference
* `?`, which just checks if a pointer is null

It's described more [here](https://branpk.github.io/wafel/docs/dev/wafel_api/index.html#data-paths).

> Why is it that you use RVAs to access the DLL's address space?

The `Address` struct holds an address relative to the base address of the DLL only so that Addresses can be shared between different DLLs (in theory - the Wafel application doesn't use this atm). They are translated to absolute addresses before they are dereferenced.

**Comment by jgcodes2020** [comment]
Also, one more thing: I noticed that the compiler always adds a `Deref` instruction before adding an `Offset` instruction. Wouldn't this fail because you would end up dereferencing an invalid pointer at some point?

Example:

`gMarioStates[0].forwardVel` would get compiled to

- `<address of gMarioStates>`
- dereference
- offset `<offset of MarioState.forwardVel>`
- dereference

When you dereference `gMarioStates` you would end up with a reference to `gMarioStates[0].unk00`. You would then add `<offset of MarioState.forwardVel>`, and subsequently try to dereference an invalid address. How does the compiler (or evaluator) avoid this?

**Comment by branpk** [comment]
`gMarioStates[0].forwardVel` gets compiled to:

* `address of gMarioStates`
* `offset 0` (because of `[0]`)
* `offset 84` (because of `.forwardVel`)

When `read` is called, an extra deref happens at the end.

**Comment by jgcodes2020** [comment]
Going to close this as it is no longer relevant
