### ISSUE TITLE
Add Building Documentation / Fix Building Issues

### ISSUE THREAD

**Issue by 1ted59** [branpk/wafel#7]
I'm trying to build from source, and I keep hitting a few road blocks such as required pip modules and the existence of the required _glslc_ program. These should be mentioned (at least the glslc program) as required.

Some mention of requiring the rust nightly build vs stable should also be mentioned, due to certain feature checks in _wafel_core_

While I have been able to find solutions to a majority of these issues, the current build that I have runs in dev-mode, and I cannot figure out how to disable that. Due to this block (and 22stars.m64 not existing) it doesn't run correctly from dev-mode unless I disable this check:
https://github.com/branpk/wafel/blob/fb03b73d493d40db0b13b747bb4de31a5601fa13/wafel/main.py#L689-L691

I have to comment out this line as well: https://github.com/branpk/wafel/blob/fb03b73d493d40db0b13b747bb4de31a5601fa13/wafel/window.py#L57 due to the ini_filename field doesn't exist on my system.

Also, upon removing this check, it says that a vanilla rom is required to operate, but I can't find documentation as to where it should go or what format that rom should be.

**Comment by sticks-stuff** [comment]
Should be noted that `pipenv install` doesn't work correctly either, it doesn't installl imgui or cython correctly. I'm presuming this is because imgui in the Pipfile points to @branpk's own custom repo? https://github.com/branpk/wafel/blob/fb03b73d493d40db0b13b747bb4de31a5601fa13/Pipfile#L11

**Comment by branpk** [comment]
Lol clearly I should have put some effort into the build before making this repo public. Sorry about this! I'll look into these issues tonight.

**Comment by branpk** [comment]
Stick, when you got the `FileNotFoundError` it might be because you ran `pipenv install` instead of `pipenv install --dev`? (I did the same thing when trying it out myself)

I made these changes:
* No longer dependent on my imgui fork, which fixes the pipenv install
* Added cargo +nightly to the build script
* Removed the hardcoded dev mode file path
* Added the locked libsm64 DLLs to the repo (which fixes the broken UI you saw asking for vanilla ROMs)
* Added build instructions to the README

@1ted59 @Thestickman391 Are you aware of any other issues that I missed here?

**Comment by sticks-stuff** [comment]
No
